name: Build and Push Docker image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    name: Build php:${{ github.ref_name }}
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ vars.DOCKER_REPOSITORY }}
        tags: |
          type=ref,event=branch
          type=sha

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max